#!/bin/sh

# Для работы скрипта необходимо создать файл настроек dump.conf в каталоге с dump.vbs и указать полный путь к файлу платформы.
# Пример C:\Program Files (x86)\1cv8\8.3.10.2252\bin\1cv8.exe

echo 'Start hooks before commit for erf and epf'

# All modified/added erf files
epfFiles=$(git status --short | grep -E '^(A|M)' | awk '{ print $2 }' | grep -E '\.erf$')

repoDir=$(pwd)

for file in $epfFiles; do
	echo 'Commit erf '$repoDir'/'$file
	wscript .git/hooks/1cv8/dump.vbs $repoDir $file
	git add .
done

# All modified/added epf files
epfFiles=$(git status --short | grep -E '^(A|M)' | awk '{ print $2 }' | grep -E '\.epf$')

for file in $epfFiles; do
	echo 'Commit epf '$repoDir'/'$file
	wscript .git/hooks/1cv8/dump.vbs $repoDir $file
	git add .
done